doc/lib_circle_nav.md
library/lib_circle_nav.ks

A set of great circle nav equations to find:
* the initial bearing along the shortest path to a point,
* the latlng() of a point a set distance along a given initial bearing from a point,
* the "as the crow flies" distance between 2 point,
* the latlng() of the mid point along the great circle path between 2 points.

lib_circle_nav

---

doc/lib_realchute.md
library/lib_realchute.ks

This isn't much of a function but there is a kOS issue requesting support for real chute and I thought this might be a way to support a mod without actually supporting it.
feel free to discard this PR if you don't think it really adds anything.

Realchute support for kOS 

---

library/lib_circle_nav.ks

bound the bearing to range (0 , 360)

bound the bearing

---

doc/lib_exec.md
examples/example_lib_exec.ks
library/lib_exec.ks

It can execute and evaluate strings.

Added exec_lib

---

examples/example_lib_raw_user_input.ks

Is it now obvious enough that it returns an index in the passed array?

Clearify examle for raw user input

---

doc/lib_ag_list_dialog.md
examples/example_lib_ag_list_dialog.ks
library/lib_ag_list_dialog.ks

@Dunbaratu Ready to merge now.
Next step: kerbal commander.

[Ready to merge] Improved interface of list_dialog and added the documentation

---

examples/example_lib_exec.ks

@Dunbaratu 
I found a really powerful use of lib_exec! Now we have lambda functions in kOS!

Improved example for lib exec

---

library/lib_ag_list_dialog.ks
library/lib_raw_user_input.ks

Don't worry. I'm going to continue improving this libraries.

Kudos and credit

---

doc/lib_lazcalc.md
examples/example_lib_lazcalc.ks
library/lib_lazcalc.ks

Adds lib_lazcalc, example script, and documentation.

lib_lazcalc initial commit

---

examples/example_lib_term_clock.ks
library/lib_term.ks

They were missing originally.  I was going to add them but it got pulled before I got home.

added copyright lines to lib_term

---

unit_tests/lib_exec/test_lib_exec_0.ks
unit_tests/lib_exec/test_lib_exec_1.internal_1
unit_tests/lib_exec/test_lib_exec_1.internal_2
unit_tests/lib_exec/test_lib_exec_1.ks
unit_tests/lib_exec/test_lib_exec_2.internal_1
unit_tests/lib_exec/test_lib_exec_2.ks

Compensating for my past laziness

Improved tests for lib_exec

---

library/lib_menu.ks

Added edge case check for lib_menu.

Fix lib_menu

---

library/lib_pid.ks

Fix lib pid

---

examples/example_lib_lazcalc.ks
library/lib_lazcalc.ks

lib_lazcalc bugfix and example improvement

---

doc/lib_lazcalc.md
examples/example_lib_lazcalc.ks
library/lib_lazcalc.ks

-Doc updated to include the name of the function.
-Doc updated to clarify that input altitude is in kilometers
-Doc updated to clarify input sterilization procedures
-Function now pulls the current vessel's inclination at the start of the
script. This avoids having two or more slightly different latitude
values being used in the calculations due to the script taking more than
one physics tick to complete
-Function will now throw an error and print a message if the input
target altitude is less than sea level
-Function now corrects impossible inclinations based on easterly or
westerly launches
-Function now prints message warning user of impossible inclination and
of automatic correction

lib_lazcalc - more improvements

---

examples/example_lib_exec.ks
library/lib_exec.ks

Evaluates a function with given arguments and returns the result.

Added evaluate_function to lib_exec

---

library/lib_raw_user_input.ks

It now doesn't use triggers and because of that it is now safer.

Improve lib raw user input

---

stripper/pack.sh

This should fix #6, at least for Unix environments.

Added stripper utility.

---

doc/lib_exec.md

lib_exec documentation update

---

doc/lib_menu.md

Spelling correction to @abenkovskii 's PR by the same name (no other changes, everything tested as working)

Lib menu documentation

---

doc/lib_lazcalc.md
examples/example_lib_lazcalc.ks
library/lib_lazcalc.ks

Lets LAZcalc be used in flight to continue updating the heading.

LAZcalc update

---

library/lib_lazcalc.ks

fixes divide by 0 error and NaN error

Lib lazcalc update

---

doc/lib_running_average_filter.md
examples/example_lib_running_average_filter.ks
library/lib_running_average_filter.ks

Simple running average filter. Tracks a settable amount of previous values and returns the average of all of those values.

lib_running_average_filter

---

doc/lib_str_to_num.md
examples/example_lib_str_to_num.ks
library/lib_str_to_num.ks

Conversion library for turning numeric strings to numbers. Supports integer, floating point, and scientific notation.

Add lib_str_to_num

---

doc/lib_enum.md
library/lib_enum.ks
specs/lib_enum_spec.ks

Work-in-progress enumerable library leveraging delegates, which are upcoming in later versions of kOS.
PR may need docs revision once the feature is actually released, but wanted to throw it up here for review. Don't merge! :)

Initial commit for lib_enum (pending 0.19.0)

---

doc/lib_pid.md
examples/example_lib_pid.ks
library/lib_pid.ks

addressing #95 
Don't opinions on whether we need more / larger explanation are welcome

Pid update

---

doc/lib_num_to_formated_str.md
examples/example_lib_num_to_formated_str.ks
library/lib_num_to_formated_str.ks

a library for changing numbers into formatted strings

add lib_num_to_formated_str

---

README.md
SUMMARY.md

Summarizes all available libraries in a single file for easy browsing. Mentions the file in README.md.
Fix: makes kOS documentation link https in the README.md.

Add SUMMARY.md

---

doc/lib_navigation.md
examples/example_lib_navigation.ks
library/lib_navigation.ks

A library consisting of plethora of functions used in calculations for both surface and orbital navigation. The example file doesn't use all functions because most functions are written with sane defaults to make them straight forward to use.

Add lib_navigation.ks

---

doc/lib_navball.md
examples/example_lib_navball.ks
library/lib_navball.ks

This should resolve the point I raised in issue #121

Lib navball improvements

---

library/lib_navigation.ks

This is a fix for the issue #123.
@scimas When you have a chance look it over and merge it.

fix for issue #123

---

doc/lib_num_to_formatted_str.md
library/lib_num_to_formatted_str.ks

Fixes #125 
Added a ROUND call for each element before padding 22d4484. 
Also added more comments for parameters and slightly modified spacing and formatting.

Fix rounding error in time_string

---

doc/lib_num_to_formatted_str.md
library/lib_num_to_formatted_str.ks
unit_tests/lib_num_to_formatted_str/README.md
unit_tests/lib_num_to_formatted_str/test_lib_num_to_formatted_str.ks

These changes are a mix of edge case fixes and performance improvements for `lib_num_to_formatted_str.ks`
Also added is a set of tests intended to be a check that the library is working as intended.

Improvments to lib_num_to_formatted_str.ks

---

examples/example_lib_num_to_formatted_str.ks
library/lib_circle_nav.ks
library/lib_enum.ks
library/lib_exec.ks
library/lib_file_exists.ks
library/lib_geodec.ks
library/lib_hyperbolic_trigonometry.ks
library/lib_input_string.ks
library/lib_input_terminal.ks
library/lib_lazcalc.ks
library/lib_list_dialog.ks
library/lib_location_constants.ks
library/lib_menu.ks
library/lib_navball.ks
library/lib_navigation.ks
library/lib_num_to_formatted_str.ks
library/lib_num_to_str.ks
library/lib_pid.ks
library/lib_raw_user_input.ks
library/lib_realchute.ks
library/lib_running_average_filter.ks
library/lib_seven_seg.ks
library/lib_str_to_num.ks
library/lib_term.ks

Adds new compiler directive to all library files.
Fixes the library files that are in violation of that directive and fixes issue #145 as a result.

kOS 1.4.x update
